apiVersion: v1
kind: Service
metadata:
  name: xp-fastapi-graphql-mysql-service
spec:
  selector:
    app: xp-fastapi-graphql-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer